### ISSUE TITLE
Client immediately crashes upon entering any interior

### ISSUE THREAD

**Issue by demiurgeQuantified** [open-toontown/open-toontown#84]
This seems to be caused by references to globalClock recently being replaced with base.clock, when ToonBase doesn't have a clock attribute.
```
  File "D:\PycharmProjects\open-toontown\toontown\building\ToonInterior.py", line 116, in enterTutorial
    base.clock.tick()
AttributeError: 'ToonBase' object has no attribute 'clock'
```
ToonInterior isn't the only file these references have been changed, so it likely causes crashes in other places too. This particular crash is caused by 1e4a7495d256e611411ec691f47041d1e1e75e4d. I'm unsure of the intent of these changes, so I don't know how best to fix it - is this relying on unpushed changes to ToonBase?

**Comment by DarthMDev** [comment]
base.clock probably needs to be defined in toonbase

**Comment by demiurgeQuantified** [comment]
Nevermind - a series of epiphanies right after submitting this issue led me to realise this was actually caused by an outdated install of the Panda3d fork 😓

**Comment by DarthMDev** [comment]
Ah i see
